"""Every error code the agent-facing contract can return, in one place (ADR-0006, issue #34).

A code is what an agent branches on, so it is stable: the message beside it
may be reworded, the code may not. `tests/test_cli_contract.py` fails if the
source raises a code that isn't listed here.
"""

from __future__ import annotations

from .domain import AGENT_ROLES

ERROR_CODES: dict[str, str] = {
    # -- the CLI itself ----------------------------------------------------------------
    "USAGE_ERROR": "the command line didn't parse: a missing argument, an unknown option or command (exit 2)",
    "INTERNAL_ERROR": "an unexpected failure inside proof-cli; the message names it",
    "INVALID_INPUT": "a legacy command (`theorem add`, `reference import`) refused its input under --json, or the page's new reference (POST /api/references) was refused; the message says why",
    "PROJECT_NOT_FOUND": "a read was pointed at a folder with no proof project; nothing was created",
    "HUMAN_REVIEW_REQUIRED": "a Human Review decision, made only by the researcher on the proof map page; the error carries its URL",
    "REVIEW_PORT_IN_USE": "`map serve` couldn't bind the project's review port because it is taken, likely by the page already running (`proof map open`); `errno` names the cause",
    "REVIEW_PORT_NOT_PERMITTED": "`map serve` isn't permitted to bind a local port: a permission or sandbox restriction; `errno` names the cause",
    "REVIEW_PORT_UNAVAILABLE": "`map serve` couldn't bind the project's review port for another reason; the message carries the system's error and `errno` its code",
    "WEB_APP_NOT_INSTALLED": "`proof home`, `proof map open` or `proof map serve` was run without the proof-web package, which serves the web app (ADR-0018)",
    # -- nodes -------------------------------------------------------------------------
    "NODE_NOT_FOUND": "no proof map node has this id",
    "NODE_ALREADY_EXISTS": "a proof map node with this id already exists",
    "INVALID_NODE_ID": "a node id must be a plain folder name: letters, digits, '.', '_' or '-'",
    "INVALID_KIND": "not a proof map node kind",
    "INVALID_TRUST_LEVEL": "not a trust level",
    "DUPLICATE_THEOREM": "the project already has its one theorem-kind node",
    "DEPENDENCY_NOT_FOUND": "a named dependency doesn't exist yet",
    "DERIVED_FROM_NOT_FOUND": "the node a split child derives from doesn't exist",
    "IMMUTABLE_NODE": "an imported result has no proof, claim or split; it enters the map through Reference review",
    "IMPORTED_RESULT_REQUIRES_SOURCE": "an imported result needs a source locator and a source version",
    "IMPORTED_RESULT_HAS_NO_DEPENDENCIES": "an imported result is established elsewhere and takes no dependencies",
    "NOT_IMPORTED_RESULT": "the operation applies only to an imported result",
    "REFERENCE_ID_NOT_IMPORTED_RESULT": "only an imported result links a reference (--reference-id)",
    "REFERENCE_NOT_FOUND": "no reference has this id: the linked citation doesn't exist here",
    "INVALID_SOURCE_TYPE": "not a reference source type (`reference import --source-type`)",
    "NOT_A_CLAIM": "only a Claim can be promoted",
    # -- claims (a planning signal, ADR-0010) --------------------------------------------
    "CLAIM_CONFLICT": "someone else holds the claim; the error names them (pass --reassign to take it over)",
    "CLAIM_CONTENDED": "the claim couldn't be taken under database contention; retry",
    "NO_ACTIVE_CLAIM": "the node has no active claim",
    "NOT_CLAIMANT": "someone else holds this node, so the operation is theirs (ADR-0006 §8's CLAIM_OWNERSHIP_MISMATCH)",
    "NODE_BLOCKED": "a dependency hasn't reached the standing this needs",
    "NODE_CHALLENGED": "the node is the target of an open Challenge",
    "NODE_ACCEPTED": "the node is Accepted; the operation would void that decision",
    "NODE_ALREADY_ACCEPTED": "the node is already Accepted",
    "NODE_REJECTED": "the node was Rejected, which is final",
    "NODE_UNVERIFIABLE": "the node's recorded decision no longer counts; it needs the researcher first",
    # -- proofs, snapshots and splits ----------------------------------------------------
    "SCOPING_RATIONALE_REQUIRED": "requesting review needs a statement of why the node is scoped to prove directly",
    "WORKING_PROOF_MISSING": "the node has no working proof.tex",
    "RUN_SCRIPT_MISSING": "a computation node has no run.sh: its review needs the program that is its candidate proof (spec #145)",
    "INVALID_MEDIUM": "the medium is not latex or computation (spec #145)",
    "MEDIUM_NOT_APPLICABLE": "an imported result has no candidate proof, so no medium (spec #145)",
    "WORKING_FILE_UNREADABLE": "a file or folder a Review snapshot would freeze, or an exchange export carry, can't be read; `path` names it, and nothing was written",
    "NODE_FOLDER_SYMLINK": "a node folder holds a symbolic link where a Review snapshot or an exchange export would read; neither follows links. `links` lists each, its `path` and whether it is `dangling`",
    "WORKING_PROOF_UNCHANGED": "the working proof is the snapshot already under review",
    "KEY_IDEAS_REQUIRED": "requesting review needs the node's key-ideas.md, with 核心思路 and 主要步骤 filled in (ADR-0013); `missing` names what is absent",
    "CANDIDATE_PROOF_NOT_FOUND": "no Candidate proof has this id",
    "REVIEW_NOT_FOUND": "no Human Review decision has this id",
    "CANDIDATE_PROOF_VERSION_CONFLICT": "that snapshot version is already indexed",
    "SPLIT_REQUIRES_CHILDREN": "a split needs at least one child",
    "INVALID_CHILD_SPEC": "a split child is written <child-id>=<statement>",
    # -- evidence, challenges, dependencies ----------------------------------------------
    "EVIDENCE_CHECK_NOT_FOUND": "no Evidence check has this id",
    "INVALID_OUTCOME": "not an Evidence check outcome (or, on `fog experiment record`, not an Experiment outcome)",
    "CHALLENGE_NOT_FOUND": "no Challenge has this id",
    "CHALLENGE_NOT_OPEN": "the Challenge is already resolved",
    "TARGET_NOT_ACCEPTED": "the target isn't Accepted",
    "TARGET_NOT_REVIEWED": "the imported result hasn't been Reference-reviewed",
    "NOT_A_DEPENDENCY": "the target isn't one of the node's dependencies",
    "ALREADY_A_DEPENDENCY": "the node already rests on that dependency",
    "DEPENDENCY_CYCLE": "the edge would close a cycle of dependencies; the error names it (`cycle`)",
    "DEPENDENCIES_CHANGED": "the node's dependencies changed since its snapshot was requested for review; request review again",
    "NO_DEPENDENCY_PIN": "the node never pinned that dependency; request review first",
    "DEPENDENCY_REQUIRED": "a Lightweight re-review names the dependency it re-pins",
    "INTERFACE_CHANGED": "the dependency's accepted interface changed: a new Candidate proof is needed, not a re-review",
    "PIN_NOT_LAGGING": "the pin already names the dependency's accepted version: there is nothing to re-review",
    # -- Human Review decisions (made on the page) ---------------------------------------
    "INVALID_DECISION": "not a decision of this kind",
    "INVALID_DECISION_KIND": "not a decision kind",
    "UNSUPPORTED_DECISION": "the page doesn't apply decisions of this kind",
    "NOT_REVIEW_NEEDED": "no snapshot awaits a decision",
    "NOT_ACCEPTED": "the node isn't Accepted",
    "REFERENCE_NOT_CALLABLE": "the imported result is no longer callable, which is final",
    "REFERENCE_STILL_CALLABLE": "the imported result is still callable, so its dependents don't move",
    "REPLACEMENT_REQUIRED": "moving dependents names the imported result they move onto",
    "REPLACEMENT_NOT_IMPORTED_RESULT": "a corrected source is cited as a new imported result",
    "REPLACEMENT_NOT_CALLABLE": "the replacement is itself no longer callable",
    "SAME_NODE": "a node can't replace itself",
    # -- Trust rules (ADR-0014; declared on the page, read-only from the CLI) ------------------
    "TRUST_RULE_NOT_FOUND": "no trust rule has this name",
    "TRUST_RULE_NAME_TAKEN": "a trust rule with this name exists, or existed: a name is never reused",
    "TRUST_RULE_RETIRED": "the trust rule is retired, which is final; declare a new one under a new name",
    "TRUST_RULE_EMPTY": "a trust rule needs at least one condition",
    "TRUST_RULE_INVALID_NAME": "a rule name is letters, digits, '.', '_' or '-', at most 64 characters",
    "TRUST_RULE_INVALID_CONDITION": "not a condition of the trust-rule vocabulary; the message names it",
    "TRUST_RULE_RATIONALE_REQUIRED": "a trust-rule decision needs a rationale",
    "TRUST_RULES_FILE_BLOCKED": "a node folder from before ADR-0014 stands where proofs/trust-rules.jsonl goes; no rule can be recorded",
    # -- Definitions (ADR-0020) -----------------------------------------------------------------
    "DEFINITION_NOT_FOUND": "no definition has this id; add it with `proof definition add` first",
    "DEFINITION_ALREADY_EXISTS": "a definition with this id exists; choose another id",
    "DEFINITION_IN_USE": "a node names this definition, so it can't be removed; edit it while it is unfixed, or add a corrected one under a new id",
    "DEFINITION_FIXED": "a Review decision relied on this definition (details.fixed_by names it): add a corrected one under a new id",
    "TEXT_FIXED": "a Review decision relied on this node's statement (details.fixed_by names it): state the correction as a new node",
    "RESEARCHER_TEXT": "the researcher wrote this text: an agent restates only text an agent created",
    "RESTATE_REASON_REQUIRED": "a restatement says why: --reason",
    "RESTATE_EMPTY": "nothing to restate: the statement, assumptions and definitions given are the node's own",
    "DEFINITION_CONFLICT": "an import brings a definition whose id is here with another text; nothing was imported",
    "DEFINITION_EMPTY": "a definition needs its term and its text",
    "INVALID_DEFINITION_ID": "a definition id is letters, digits, '.', '_' or '-', at most 64 characters, starting with a letter or digit",
    # -- Proof fog (ADR-0008, spec #136; ungated, outside the map) -----------------------------
    "FOG_NOT_FOUND": "no fog item has this id",
    "FOG_NOT_OPEN": "the fog item is dropped (reopen it first) or crystallized (its node exists now); the message says which",
    "FOG_TEXT_REQUIRED": "a fog item needs its text",
    "FOG_REASON_REQUIRED": "dropping a fog item needs a reason",
    "FOG_RUN_BY_REQUIRED": "an Experiment records who ran it (--run-by)",
    "FOG_SUMMARY_REQUIRED": "an Experiment says what was computed and what it showed (--summary)",
    "FOG_FLAG_CONFLICT": "two flags that exclude each other were given: --parent with --no-parent, or --near with --clear-near",
    "FOG_EXPERIMENT_PATH_INVALID": "an Experiment's path is relative, under proofs/, and exists when recorded",
    "FOG_PARENT_AMBIGUOUS": "the fog item is near several nodes: name the parent with --parent, or --no-parent",
    "NO_DEPENDENTS": "nothing that can move rests on the node",
    "STALE_VIEW": "what the decision is made on changed since the page showed it; reload",
    "SNAPSHOT_UNREADABLE": "the Review snapshot the decision would be made on is missing or can't be read, so nothing is decided on it",
    # -- publication: the editorial track (issue #30; editorial, not Human Review) ------
    "PUBLICATION_NOT_ACCEPTED": "only a node that is accepted · current may be marked supplement_ready or paper_ready; the error carries its acceptance and integrity",
    "PUBLICATION_NO_ACCEPTANCE_AXIS": "a theorem_contract claim has no acceptance axis, so it can't be marked supplement_ready or paper_ready",
    "INVALID_READINESS_TRANSITION": "the editorial track doesn't allow this move; the error lists the allowed states",
    "INVALID_READINESS": "not an editorial readiness state",
    "INVALID_AUDIENCE": "not a publication audience (internal, supplement, paper)",
    "INVALID_RELEASE_STATUS": "not a release status (approved, corrected, withdrawn)",
    "INVALID_CITATION_KIND": "not a publication citation kind",
    "INVALID_OBJECT_TYPE": "a publication claim is on a proof_map_node or a theorem_contract",
    "THEOREM_NOT_FOUND": "no theorem contract has this id",
    "PUBLICATION_CLAIM_NOT_FOUND": "no publication claim for this object",
    "RELEASE_NOT_FOUND": "nothing was released under this release id or bundle id",
    "UNSUPPORTED_FORMAT": "not a publication export format (paper, supplement, bundle, manifest)",
    # -- exchange (#31): a rejected import writes nothing; `problems` lists every one ---------
    "BUNDLE_UNREADABLE": "the bundle file couldn't be read",
    "MALFORMED_BUNDLE": "the input isn't JSON, or doesn't match the exchange bundle schema",
    "IMPORT_ID_CONFLICT": "a record the bundle would add reuses an id this project (or the bundle itself) already uses",
    "INVALID_VAULT_PATH": "a Candidate proof file_path or vault file isn't a relative path inside its node's proofs/<node-id>/ folder",
    "VAULT_FILE_MISSING": "an imported Candidate proof's snapshot isn't carried whole in the bundle",
    "VAULT_HASH_MISMATCH": "a vault file doesn't match its SHA-256, or a snapshot doesn't match the SHA-256 its index records",
    "VAULT_FILE_CONFLICT": "a vault file would overwrite a different file already here",
    # -- the proof map page's own requests -----------------------------------------------
    "NO_DECISIONS": "the request decided nothing",
    "MALFORMED_DECISION": "a decision in the request isn't a well-formed object",
    "NO_PDF": "that PDF doesn't exist",
    "NO_SUCH_FILE": "the node's current snapshot froze no file by that path",
    "NO_PROOF_FOLDER": "the node has no proof folder",
    "INVALID_REQUEST": "the page's request is missing what the action needs (a node id, which snapshot, …)",
    "NOT_FOUND": "no such page route or node action, or (a legacy command under --json) no such contract, reference or target",
    "NOT_THIS_NODE": "the snapshot, Candidate proof or review named belongs to another node",
    # the page's write checks, before any action runs (ADR-0007)
    "WRONG_HOST": "the request names another host than the app's pinned origin",
    "WRONG_ORIGIN": "a write came from another origin than the app's own page",
    "JSON_REQUIRED": "a write's body is application/json",
    "BAD_LENGTH": "the request's Content-Length is missing a number or negative",
    "BODY_TOO_LARGE": "the request body is larger than the app accepts",
    "MALFORMED_JSON": "the request body isn't a JSON object",
    # -- a node's studio (ADR-0011), and a computation's Run and Open in VS Code (ADR-0015, spec #145) --
    "NO_STUDIO": "an imported result has no studio: it has no proof to write",
    "STUDIO_CLOSED": "the studio is closed: the proof map's server is shutting down",
    "CROSS_SITE": "the studio answers only its own page",
    "NOT_A_COMPUTATION": "Run is for a node whose Medium is computation; a LaTeX node compiles",
    "NOT_A_NODE_FILE": "the file to open is not an editable file of this node's folder",
    "INVALID_LINE": "the line to open a file at is a positive whole number",
    "OPEN_FAILED": "the project's [studio] open_command could not start, or exited non-zero",
    "NOT_UTF8": "the file is not UTF-8 text; the studio edits UTF-8 files only",
    "STUDIO_REQUEST_INVALID": "the studio's request is malformed or names something it may not touch; the message says what",
    "STUDIO_FILE_ERROR": "the studio could not read or write a file (locked by another program, say); the message says which",
    "NO_SUCH_JOB": "no agent job of this studio by that id",
    "NO_SYNCTEX": "no SyncTeX data yet: build first",
    "NO_SYNCTEX_MATCH": "SyncTeX knows no place for that position",
    "EVIDENCE_SNAPSHOT_MISMATCH": "the snapshot hash an Evidence check names is not the snapshot's hash now; the message names the node's current snapshot",
    # -- the Home (ADR-0017): the project list in front of the map ------------------------------
    "PATH_REQUIRED": "the Home's request names no folder",
    "PROJECT_UNKNOWN": "the folder isn't in the project list; add it first",
    "FOLDER_NOT_FOUND": "no folder at that path",
    "NOT_A_PROJECT": "the folder holds no proof project (no .proof/project.sqlite3); create one there instead",
    "ALREADY_A_PROJECT": "the folder already holds a proof project; add it instead of creating one",
    "BAD_PROJECT_ID": "a project id must be a non-empty string",
    "CANNOT_CREATE": "the project folder couldn't be made or written",
    "PORT_BUSY": "the project's own port is taken by something that isn't its page",
    "PROJECT_REPLACED": "the page, studio or run was opened for a project that is no longer in its folder (deleted and started again there); nothing of the new project is read or written through it",
    # -- the Proof agent's work log (ADR-0016, spec #145) --
    "ROLE_REQUIRED": "a progress report names the role that makes it: PROOF_AGENT_ROLE in the agent's runtime, or --role",
    "INVALID_ROLE": f"the Proof agent role is not one of {', '.join(AGENT_ROLES)}",
    "INVALID_PROGRESS_STATUS": "a step's status is started, done, stuck or needs-human",
    "INVALID_PROGRESS_STEP": "steps count from 1",
    "PROGRESS_STATUS_REQUIRED": "a step report needs its status",
    "PROGRESS_EMPTY": "a progress report is a plan, a step, a handoff, a verdict, an attempt or a choice made (--question); this one is none of them",
    "DECISION_REQUIRED": "a step that needs a human decision names the decision in --note",
    # -- the Verifier's verdict and the record of attempts (ADR-0019 parts A and B) --
    "VERDICT_ROLE_REQUIRED": "only the verifier role records a verdict; the message names the role that tried",
    "INVALID_VERDICT": "a verdict's outcome is passed or failed",
    "OBJECTIONS_REQUIRED": "a failed verdict names its objections in --note",
    "QUESTION_NOT_FOUND": "the node has no Standing question with that id",
    "QUESTION_ANSWERED": "the Standing question was already answered; a further redirect goes to the node's run",
    "ANSWER_REQUIRED": "an answer keeps the choice (--keep) or gives the other reading (--answer), exactly one",
    "ANSWER_IS_THE_RESEARCHERS": "a Standing question is answered by the researcher, not by a Proof agent",
    "ATTEMPT_INCOMPLETE": "an attempt is recorded by what it tried to establish and what it failed on: --attempt needs --failed-on",
    "GATE_MALFORMED": "`request-review --gated-by` is one SHA-256 of 64 hex digits, given once; a repeated, empty or malformed value is refused rather than read as no gate",
    "VERDICT_STALE": "a run's Prover requested review naming a passing verdict's digest (--gated-by), but the node's files are no longer the ones the Verifier passed, or the text it read them against was restated since; nothing was frozen",
    # -- the Proof agent's run, through the studio and the map (ADR-0016, spec #145) --
    "RUN_ACTIVE": "an agent is already working on this node: pause, redirect or release it first",
    "RUN_SETTLING": "the previous run is still giving the node back; Start again in a moment",
    "RUN_GONE": "the node's run could not be reached: its node is gone from the map, or its studio is closed",
    # the Decomposer, started alone on a Theorem not yet split (ADR-0019 point 20)
    "ROLE_ALONE": "the Decomposer is started on its own, for one turn; it is not part of a run with other roles",
    "NOT_DECOMPOSABLE": "the Decomposer works a Theorem or Lemma not yet split: this node is a Claim or an imported result, or already rests on the Claims a split made",
    "NO_RUN": "no agent run to act on: the folder is not a proof map node, or no run is active on it",
    # the Coordinator over a Theorem's or Lemma's subtree (ADR-0019 point 18)
    "NO_SUBTREE": "no subtree to coordinate: the node rests on nothing, or is an imported result",
    "COORDINATOR_ACTIVE": "a Coordinator is already working this subtree: pause or stop it first",
    "NO_COORDINATOR": "no Coordinator is working this subtree",
    "NOT_PAUSED": "the Coordinator is not paused",
    "NOTHING_OPEN": "nothing in the subtree is open: every node is Accepted, or none has a proof to write",
    "COORDINATOR_REFUSED": "the Coordinator refused the action; the message says why",
    "REDIRECT_EMPTY": "a Redirect needs its one line of text",
    # the map-level discussion (issue #177)
    "PROMPT_EMPTY": "a message to the map's agent needs its text",
    "AGENT_REFUSED": "the agent's turn could not start for a reason with no code of its own; the message says why",
    "RUN_REFUSED": "the run's Start was refused for a reason with no code of its own; the message says why",
    "RELEASE_FAILED": "the run ended but the node could not be given back; it is still assigned, and the message says why",
    "AGENT_BUSY": "the studio's agent is still working on the previous turn",
    "KEY_IDEAS_AGENT_TURN": "an agent's edit turn is running on this node; key-ideas.md is saved from the page once it ends, so the save stays the researcher's (ADR-0013)",
    "NO_SUCH_TURN": "no turn of a run on this node was recorded under that id",
    "AGENT_UNKNOWN_PROVIDER": "the studio has no agent backend by that name (claude, codex)",
    "AGENT_UNAVAILABLE": "the agent's CLI can't run a turn here: not installed, not logged in, or it refused; the message says why",
    "AGENT_INVALID_OPTION": "the model or effort asked for is not one the agent's CLI accepts",
    "AGENT_NO_USAGE_LIMITS": "this agent backend reports no usage limits to probe",
    "TURN_CALLED_OFF": "the run was stopped while its turn was being prepared, so no turn started",
}


NOTICE_CODES: dict[str, str] = {
    # A notice is what a command that succeeded has to tell its caller, never a refusal: under
    # --json it is `data.notices`, a list of {code, message, …}; the code is stable like an error's.
    "SNAPSHOT_LARGE_OUTPUT": "the Review snapshot froze more of a computation's out/ than `[snapshot] large_output_mb` in proof.toml (default 50); `output_bytes` and `threshold_bytes` say how much (spec #145)",
    "SNAPSHOT_SKIPPED_HIDDEN": "the Review snapshot left hidden files or folders out (secrets, dotfiles not on the allowlist, hidden folders); `paths` lists them by path, never their contents (ADR-0015)",
    "SNAPSHOT_EXPORTED_UNVERIFIABLE": "an exchange export left frozen files out of a snapshot (secrets, or hidden or cache files an older rule froze), so it no longer verifies where it is imported; `node_id`, `version` and `paths` say which (ADR-0015)",
    # the mechanical checks of a node's working proof (`proof node check`, issue #180): findings, never refusals
    "CHECK_PROOF_MISSING": "the node's working proof.tex is not there (node check)",
    "CHECK_RUN_SCRIPT_MISSING": "a computation node's run.sh is not there (node check)",
    "CHECK_NOT_BUILT": "proof.tex has not been compiled: build/proof.pdf is missing (node check)",
    "CHECK_BUILD_STALE": "an input changed after the last build: compile again (node check)",
    "CHECK_COMPILE_ERRORS": "the last build's log has errors (`!` lines); the first is in the message (node check)",
    "CHECK_UNDEFINED_REFERENCES": "the last build's log reports undefined references or citations (node check)",
    "CHECK_STATEMENT_MISMATCH": "the node's statement, as the map has it, does not appear in proof.tex (node check)",
    "CHECK_INPUT_OUTSIDE": "proof.tex \\input's a file outside the node folder and the shared preamble (node check)",
    "CHECK_INPUT_UNREADABLE": "a file proof.tex \\input's could not be read, so the checks cannot see it (node check)",
    "CHECK_KEY_IDEAS_MISSING": "key-ideas.md is not there; request-review needs it (node check)",
    "CHECK_KEY_IDEAS_HEADINGS": "key-ideas.md lacks one of its four headings (node check)",
    "CHECK_KEY_IDEAS_EMPTY": "key-ideas.md has an empty required section (核心思路 or 主要步骤) (node check)",
    "CHECK_KEY_IDEAS_UNKNOWN_NODE": "key-ideas.md's 主要步骤 names a node that is not on the map (node check)",
    "CHECK_DEPENDENCY_UNMENTIONED": "a dependency of the node is named neither in proof.tex nor in key-ideas.md (node check)",
}


def notice(code: str, message: str, **data) -> dict:
    """One notice, as `data.notices` carries it; `code` must be in NOTICE_CODES (KeyError otherwise)."""
    NOTICE_CODES[code]
    return {"code": code, "message": message, **data}
